#GET ALL (FLY)
GET https://phonebook-backend-jordijs.fly.dev/api/persons

###
#GET BY ID (FLY)
GET https://phonebook-backend-jordijs.fly.dev/api/persons/1

###
#GET ALL (localhost)
GET http://localhost:3001/api/persons

###
#GET BY ID (localhost)
GET http://localhost:3001/api/persons/6671802f6835d9db058147d6